runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:

- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico

- url: /static
  static_dir: static

- url: /static/img
  static_files: keroro.png
  upload: keroro.png

- url: /.*
  script: main.app

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(Include/.*)
- ^(Scripts/.*)
- ^(tcl/.*)

# [END handlers]
